server:
  port: 8881
  servlet:
    context-path: /filxeservice
spring:
  application:
    name: filxeservice
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
filxeservice:
  file:
    store:
      # /Volumes/DYZ-document/Program/X-CodeRunSpace/store/
      # C:\var\dyz\store
      path: /Volumes/DYZ-document/Program/X-CodeRunSpace/store/
      temp-path: /Volumes/DYZ-document/Program/X-CodeRunSpace/temp/
logging:
  config: classpath:log4j2.xml

eureka:
  instance:
    # 使用服务的IP而不是服务器名称，确保在容器环境下正常
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/