server:
  port: 8881
  servlet:
    context-path: /filxeservice
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
filxeservice:
  file:
    store:
      path: /Volumes/DYZ-document/Program/WorkFolder/
logging:
  config: classpath:log4j2.xml