server:
  port: 8881
  servlet:
    context-path: /filxeservice
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
filxeservice:
  file:
    store:
      # /Volumes/DYZ-document/Program/WorkFolder/
      path: C:\var\dyz\store
logging:
  config: classpath:log4j2.xml